### PR TITLE
usddeck: Add eventriggerType_fp16

### PR DESCRIPTION
**Pull request by jonasdn**
Fixes: #798

### CODE REVIEW

**Review by whoenig — APPROVED** [review]
Do we actually have variables of this type? Your code changes look good, but I am worried about proper support on the host side. In particular, does struct.decode do the right thing and is the firmware actually using the IEEE 754 binary16 standard? Supporting this datatype on a C++ host might also be challenging, as this is none of the standard types in C(++).

**Comment by jonasdn** [comment]
> Do we actually have variables of this type? Your code changes look good, but I am worried about proper support on the host side. In particular, does struct.decode do the right thing and is the firmware actually using the IEEE 754 binary16 standard? Supporting this datatype on a C++ host might also be challenging, as this is none of the standard types in C(++).

Good questions!

Python supports this since I think 3.6: https://docs.python.org/3/library/struct.html#format-characters, and I believe it should work. And according to @ataffanel this should work (https://forum.bitcraze.io/viewtopic.php?p=22023&sid=311d5a4e46d027554d6e04312f573ebd#p22023).

I think both clang and gcc has extensions to support this. But! Your objections are fair. Perhaps instead of this PR we make it not assert and instead warn in some way?

**Comment by whoenig** [comment]
My (bold) suggestion would have been to just remove FP16 entirely from the firmware - less to test & maintain... I don't remember seeing it being used inside the firmware and I've also not really seen the feature being used to log data with a different type (e.g., logging a float32 variable as FP16 to fit more inside a single log block.)

**Comment by ataffanel** [comment]
There is currently no variable that uses FP16 in the firmware memory, this is only converted to be transferred in the log packets.

My intention was to implement IEEE 754 binary16 when I implemented FP16 in the Crazyflie. From my tests, the python implementation works fine with it. I do not remember being too careful about rounding and subnormalized representation is not handled, but for the purpose of compressing floating point representation it works well. For reference, the implementation is there: https://github.com/bitcraze/crazyflie-firmware/blob/a70c357a7c03b84a0caebe6d31a5fb0ccc40ff2b/src/utils/src/num.c#L48-L62.

Now, when it comes to the SD-card deck, it may be that fp16 is not that interesting since we have a lot more bandwidth. Though if it can be handled rather than failing it would be more coherent and less surprising if anyone tries to use it.

GCC support for fp16 was added right after I made my own implementation, it might also be an idea to use it in the Crazyflie so that we can be a bit more confident with interoperability.

**Comment by ataffanel** [comment]
> My (bold) suggestion would have been to just remove FP16 entirely from the firmware - less to test & maintain... I don't remember seeing it being used inside the firmware and I've also not really seen the feature being used to log data with a different type (e.g., logging a float32 variable as FP16 to fit more inside a single log block.)

It is implemented in the Crazyflie lib now. I was implemented to make this packet possible using a single log block:
https://github.com/bitcraze/crazyflie-lib-python/blob/master/examples/basiclog.py#L75-L84

I do think that it is a useful functionality when it comes to the radio since we have such a limited space in each log packet.

**Comment by whoenig** [comment]
For this particular case, I think it makes more sense to use `pm.vbatMV` (https://github.com/bitcraze/crazyflie-firmware/blob/6b04364847c5a2d6cbcb695395152e655c11b1fd/src/hal/src/pm_stm32f4.c#L421).

But going back to the topic at hand: if fp16 is to remain supported, then this PR looks good.

**Pull request merged**
