### PR TITLE
Heap management options

### PR DESCRIPTION
**Pull request by pablogs9**
This PR enables OOT apps to overwrite MEMMANG_OBJ with a custom implementantion of the heap manager.

It also enables the build system to set FREERTOS_HEAP_SIZE from CFLAGS.

### CODE REVIEW

**Comment by ataffanel** [comment]
This looks good, I am merging it, thanks!

One side note about that: we are planning on removing all dynamic memory allocation from the Crazyflie firmware itself since it does not fit very well with hard real-time. In a sense it makes this PR more relevant though since only the app layer might then be interested in dynamic memory.

**Comment by pablogs9** [comment]
I've read something about this migration to static memory, the v10 version of the kernel (merged in #510) allows this static allocation of tasks, queues, etc. Thaks for the merge :).

**Comment by pablogs9** [comment]
@ataffanel is this PR going to be in next-release milestone? Thanks

**Comment by ataffanel** [comment]
Yes sure, we release the tip of the master branch, so everything that is in master will be released.

**Pull request merged**
