### PR TITLE
Add tools/build/elf_sanity.py

### PR DESCRIPTION
**Pull request by jonasdn**
This script uses pyelftools to check the elf output file.

In this first version it will make sure that the added parameters are
not duplicates and does not exceed the max length of 25 characters.

This is hard to do in compile-time with macro magic.

### CODE REVIEW

**Comment by krichardsson** [comment]
Nice!
I think it should be added to the master build script ```tools/build/build``` to run it in CI and so on as well.

**Comment by krichardsson** [comment]
We have long discussed some form of documentation of log and params, could an extension of this functionality possibly be a part of that? For instance generating lists of logs and params to be able to see what is available and what has been added/removed between releases?

**Comment by jonasdn** [comment]
> We have long discussed some form of documentation of log and params, could an extension of this functionality possibly be a part of that? For instance generating lists of logs and params to be able to see what is available and what has been added/removed between releases?

This is possible, the what and how should be discussed.

**Comment by ataffanel** [comment]
This is a long needed addition. Looks great!

**Pull request merged**
