### PR TITLE
dev/tdoa3 plus

### PR DESCRIPTION
**Pull request by Williamwenda**
Add tdoa3_plus
enable inter-drone ranging together with TDOA3 measurements from anchors.

### CODE REVIEW

**Comment by krichardsson** [comment]
Hi Wenda!

I have (finally) started to look at this pull request. To make it easier for me to digest the changes, could you briefly explain the functionality that has been added/modified to TDoA3 (in lpsTdoa3Tag.c) and the new TDoA4 (in lpsTdoa4Tag.c). What is the difference between TDo3+ and TDoA4 and how is it intended to be used?
I also see that you have added a CRTP broadcast functionality, how is that used? 

Thanks!

**Comment by Williamwenda** [comment]
Hi Kristoffer,

The functionalities of TDoA3+ and TDoA4 are as follows.
TDoA3+:  enables the toda measurements with TDoA3 tag protocol and
inter-drone ranging with TDoA3 anchor protocol.
TDoA4:    enables inter-drone ranging with TDoA3 anchor protocol.

The functionalities are elementary now.
For TDoA3+, it would be interesting for hybrid TWR and TDoA localization.
For TDoA4, it would be interesting for inter-drone
communication and relative localization.

The changes for CRTP protocol is used for sending Vicon measurements and
way-point commands from our ground station.
It is not related to the UWB development.

This is the first step for the new LPS functionality. We can discuss how we
wish to use the inter-drone ranging capability and
develop the code for that purpose.

KInd regards,

Wenda

**Comment by krichardsson** [comment]
Thanks!
I'll dive into the code and poke around a bit :-)

- Kristoffer

**Comment by krichardsson** [comment]
Hi @Williamwenda !

I have spent some time looking into this. Even though the concept of adding TWR ranging in TDoA3 seems to be pretty straight forward, there are lots of dependencies/implications on other modules and many things to take into consideration. It is important to make new functionality useful for as many users as possible while keeping it out of the way for users that are not interested in the functionality.

Some examples of things to take into consideration are:
* How to implement this without making the code too complex
* How to separate the functionality to keep it clean
* How to integrate with existing modules, for instance the peer_localization module and estimator
* There is very limited space left in the LPS anchors for additional functionality or RAM usage. Preferably the TDoA3 protocol should be unchanged which would keep the necessary changes in the anchors at a minimum.
* How to communicate the std of the position for a device that is transmitting? Maybe we do not want to trust the position of a moving Crazyflie as much as a static anchor for instance?
* How to configure/manage how often a CF will transmit (TWR) VS passively listen (TDoA)
* There are also other on-going projects that are touching the same areas of functionality that we must fit in as well.

I have started to digest the full picture but I think it will take some time, as we (Bitcraze) have to figure out how we want to evolve this part of the system. We'll keep you updated.

**Comment by Williamwenda** [comment]
Hi Kristoffer,

Thanks for the updates! Let me know if there is anything I can contribute.

Kind regards,

Wenda

**Comment by keffklau** [comment]
Hello Kristoffer, hello Williamwenda, 

this is really a great feature! I can't wait to have a closer look - but unfortunately, the earliest date to really start working will be in the middle of spring. 
However: It would be great, if one could include the position of the CF where the range measurement is referring to (I suppose this is included, since this information is also provided for the normal anchors) and uncertainty information concerning the quality of this position information from the CFs state estimator (position variance), e.g. three additional values.....

**Comment by krichardsson** [comment]
Hi Klaus!
Yes, in the standard TDoA3 implementation, the position is included in all packets sent by the anchors. The position is appended as a LPP packet https://github.com/bitcraze/lps-node-firmware/blob/2020.09/docs/protocols/lpp-short-packets-protocol.md
I agree that we should add uncertainty information. One way could be to append it as separate LPP packet after the position information to maintain compatibility with the current firmware, but I'm not sure yet what would be the best solution.

**Comment by krichardsson** [comment]
Related to #576

**Comment by krichardsson** [comment]
Hi @Williamwenda !
I have looked at this PR and done a fair bit of thinking to figure out how implement inter drone ranging / TDoA3+ / TDoA4 in the best way. I tried to write down my ideas in #576, please take a look and let me know what you think.

**Comment by Williamwenda** [comment]
Hi Kristoffer,

Sure, I will have a look. For the robust Kalman filter PR, I received some
comments from knmcguire. I answered her questions about the code but didn't
hear back after that. Could you please follow up on that PR as well? Thank
you!

Wenda

**Comment by knmcguire** [comment]
I believe that this has already been merged, or at least a good part of it with #707. I'll close these!

**Pull request closed without merging**
