### PR TITLE
Indi controller

### PR DESCRIPTION
**Pull request by andre-paraense**
Implementation of a third option of controller, known as the "Incremental Nonlinear Dynamic Inversion (INDI) controller".

For more information, see issue #446 .

### CODE REVIEW

**Comment by knmcguire** [comment]
Hi! Thanks a lot for the pull request. We will review and try it out this week somewhere, just to make sure it works out. I would love to see INDI work on the Crazyflie :)

First thought though : There are a lot of commits... Would it be possible to squeeze those all in one if there aren't any merges from the master branch in the mean time?

**Comment by andre-paraense** [comment]
This INDI controller feels really good, it is very smooth to control the Crazyflie. This is only the first version, which controls the attitude inner loop, there is still the possibility of implementing the position outer loop as well and then it will be even better! :)

About the squash of the many commits, isn't it easier if you just choose the [squash and merge](https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits) option when you finally decide it is good to go?

**Comment by knmcguire** [comment]
Ah yes ofcourse that is true. my bad.

I will review it soon this week and try it out :).

**Comment by knmcguire** [comment]
I just tried out your branch and INDI is working error free but not as swiftly as PID. There seems to be a limit on the angles? And have you estimated the motor effectiveness and implemented those values (and is it for the crazyflie 2.0 or 2.1)?

I will dig into the code a little bit more deeper this week, but I saw in your commits that you first put the estimator in the firmware and then removed it again & added an external tool. Could you let me know why this is?

It would be good as well to provide a global list of what you have added to the firmware and the functionality, to make it easier for us to review your code. It is quite a lot and we just want to make sure that it is integrating nicely into the rest. 
Thanks!

**Comment by andre-paraense** [comment]
> I just tried out your branch and INDI is working error free but not as swiftly as PID. There seems to be a limit on the angles? And have you estimated the motor effectiveness and implemented those values (and is it for the crazyflie 2.0 or 2.1)?
> 

I did estimate the actuator dynamics and control effectiveness, but to be honest I did so using the PID controller. It can be improved if the process is done again this time using the INDI controller, now that it is able to fly.  I could do this quite fast, however I lost access to the Crazyflie with SD-Card because it was damaged and lost, and now I have other priorities here. If you want to go further on this, I would be happy to assist you through the process. The process is very simple, indeed: first you would have to fly with the INDI controller and the SD-Card attached, so we could log the signals in high frequency (500Hz) using the [file I already used and made available](https://github.com/amreelab/crazyflie-firmware/blob/indi-controller/tools/param_est/config.txt) first with the PID controller. Then I could take a look and show you if there are any apparent improvements to be made,changing the actuator dynamics constant to align the signals. We could also have the help of Dr. Ewoud Smeur for that, he already helped with the first estimation using the PID. Is this clear to you? I mean, maybe I should have said that these parameters are estimated using flight data. In the beginning, as the INDI controller does not fly well, we estimate them using another controller, for instance the PID. This was already done. After that, we use the values to start flying with the INDI, but then we can redo the process to further improve it. I also forgot to mention that the flight exercise to log the data should be very simple, just try to fly around in all directions, but avoid touching the floor or the ground, as this could be interpreted as a result of the control signal. Just fly around making movements in all pitch, roll and yaw directions and then land and stop the connection, and handle me the log file, I can do the rest for us.

> I will dig into the code a little bit more deeper this week, but I saw in your commits that you first put the estimator in the firmware and then removed it again & added an external tool. Could you let me know why this is?
> 

The part removed was related to the adaptive INDI controller, that is, a controller which adapts the actuator dynamics and control effectiveness in real time. This was a suggestion from Dr. Ewoud Smeur: first code and release a simple INDI controller, without the online adaptive feature, then later implement it. There are indeed some other very interesting additions to be made, following Dr. Smeur's publications. This first version is the simplest one: INDI only for the attitude (not yet for the [position control](https://www.sciencedirect.com/science/article/pii/S0967066118300030)) and without [adapting in real time](https://arc.aiaa.org/doi/abs/10.2514/1.G001490). Adapting in real time is good for many reasons, which is further explained in Dr. Smeur' s [publication](https://arc.aiaa.org/doi/abs/10.2514/1.G001490), one very simple, for instance, is that the actuators (motors) dynamics change as battery drains, because the input voltage changes. Other more complex examples would be gust disturbances, loss of part of the vehicle due to impact, and so on.

> It would be good as well to provide a global list of what you have added to the firmware and the functionality, to make it easier for us to review your code. It is quite a lot and we just want to make sure that it is integrating nicely into the rest.
> Thanks!

Basically I have added two things:

1 - INDI controller: added a third option of controller, alongside with the two previous ones available, which were the PID and the Mellinger. I did my best to follow the interface that was already coded, parameterize everything (so could be changed through the cfclient), and so on. I think in the end the integration was very reasonable, and we are capable of changing to the INDI controller over the cfclient quite easily. Also all of the parameters (including control effectiveness and actuator dynamics) are available in the cfclient parameter tab to be changed in real time as well, if the user wants. This addition of the INDI controller spreads around some files, I will list them here:
- `Makefile`
- `src/modules/interface/controller.h`
- `src/modules/interface/controller_indi.h`
- `src/modules/interface/controller_mellinger.h` (just corrected a typo in this file)
-  `src/modules/src/controller.c`
- `src/modules/src/controller_indi.c`
-  `src/modules/src/controller_mellinger.c` (added logging variable to help us estimate actuator dynamics and control effectiveness through flight data using this controller)
- `src/modules/src/controller_pid.c`  (added logging variable to help us estimate actuator dynamics and control effectiveness through flight data using this controller)
- `src/utils/interface/filter.h` (added second order Butterworth filter as an option, which is used by the INDI controller)
- `tools/make/platforms/cf2.mk`
- `tools/make/platforms/tag.mk`

2 - Parameters estimation tools: the second package added comprises tools to support the estimation of the actuator dynamics and control effectiveness through flight data. This are going to be matlab and python scripts to process the flight data and log config files, and will be concentrated in the `tools/param_est` package:
- `tools/param_est/CF_functions.py`
- `tools/param_est/config.txt`
- `tools/param_est/control_effectiveness_estimation.m`
- `tools/param_est/extract_signals.py`

I hope this helps. Please let me know if you have any doubts.

**Comment by knmcguire** [comment]
Hi Andre,

Sorry I was not able to check out your tips yet! Wee have been swamped the last few weeks with our trips :(  This week is not any better but next week or in 3 weeks we will start working on it again. 

Just a very quick comment, the tools you provide, we see a mixture of python and matlab files. Would it be possible to provide those completely in python? Or are those matlab files also compatible with Octave?

**Comment by andre-paraense** [comment]
> Hi Andre,
> 
> Sorry I was not able to check out your tips yet! Wee have been swamped the last few weeks with our trips :( This week is not any better but next week or in 3 weeks we will start working on it again.
> 
> Just a very quick comment, the tools you provide, we see a mixture of python and matlab files. Would it be possible to provide those completely in python? Or are those matlab files also compatible with Octave?

Hi, Kimberly. That is absolutely OK, take your time. The matlab files are fully compatible with Octave. I have used Octave myself.

**Comment by knmcguire** [comment]
Hi!

This pull request has been on a low for a while, sorry about that! The parameters still needs some tuning but since the integration is the right way and it is not selected by standard, we will go ahead and merge it while it is still mergable :). 

Thanks again!

**Comment by andre-paraense** [comment]
This is great decision, thank Kimberly. This way the code won' t get outdated and we have the possibility of improving parameters and implementation in future PRs.

cc @EwoudSmeur

Cheers!

**Comment by knmcguire** [comment]
Hi @andre-paraense, we have a forum post about issues in the INDI controller. Would you take a look at it and give some feedback ? Thanks!

https://forum.bitcraze.io/viewtopic.php?f=6&t=4786

**Comment by knmcguire** [comment]
Thanks for answering! By the way, I am organizing a INDI get together with some of the contributors involved to talk about the controller. If you are interested, please send us a mail at contact_at_bitcraze.io

**Pull request merged**
