### PR TITLE
Doc 2022.01

### PR DESCRIPTION
**Pull request by knmcguire**
Documentation fixes for the new release. Mostly focusing on updating and fixing wrong linking and errors here. 

I'll keep it in draft until it's ready to merge

### CODE REVIEW

**Comment by knmcguire** [comment]
Some future updates still necessary, which are immortalized by these issues opened:
CRTP updates: #762 
Subsystem info: #921
pwm thrust table update: #908

**Review by jonasdn — APPROVED** [review]
Looks good to me! Great job!

**Comment by knmcguire** [comment]
I still have to make some changes to the build and install instructions I just found out, in particular the windows building part

**Comment by knmcguire** [comment]
New build instructions of windows are coming up still today. For now I'll merge this to double check this with the webbuilder as there are so many changes

**Comment by knmcguire** [comment]
Hi! That page was actually moved some time ago to the product page: https://www.bitcraze.io/products/micro-sd-card-deck/, but we forgot to remove it in the repo doc.

You can find it under usage and development.

**Comment by matejkarasek** [comment]
Ah, there it is, missed that, thanks :)
FYI, in the "How it works" section, if you click the "MicroSD card deck", the "Logging guide" still links to the old location...

**Comment by knmcguire** [comment]
ah oke! so that was in the poplinks structure still. For the next deployment this will be removed. 

We need to start rethinking the website a bit... to many links and too much content on many places.

**Pull request merged**
