### PR TITLE
CPX documentation

### PR DESCRIPTION
**Pull request by evoggy**
This documents the inner workings of CPX.

### CODE REVIEW

**Comment by evoggy** [comment]
This is still work in progress, but I'll leave it here so we can have a look at it. It also contains some stuff that's not true yet, like CPX over CRTP. Let's see how this progresses otherwise we remove it :smile: 

Should we also add some information about the APIs at the end (like structs and C/Python APIs) or this should be in each of the repositories where this is implemented?

**Review by krichardsson — COMMENTED** [review]
Looks good!

Diitaa is supported for repo docs if you want fancier diagrams https://www.bitcraze.io/development/contribute/repo-doc-guidelines/#diagrams

**Comment by evoggy** [comment]
Nice, forgot about that! Updated the diagrams now to use ditaa instead.

The MTU of a packet which will not be split is still TDB. What about setting this to 30 bytes?

**Comment by evoggy** [comment]
30 bytes was decided for the MTU.

**Pull request merged**
