### PR TITLE
Log motor PWM ratios after voltage compensation

### LINKED ISSUE #77: Add log for real motors PWM
Currently the motor PWM ratio logging is done before battery voltage compensation. It would be useful to add log variables after the battery voltage compensation to get the PWM ratio actually applied to the motors.

### PR DESCRIPTION
**Pull request by ograff**
Update motors.c to log PWM ratios after voltage compensation. Fix #77

### CODE REVIEW

**Comment by ograff** [comment]
D'oh, looks like this overflows RAM. I'll see if I can come up with a way to grab this info from where it already exists, instead of storing it twice

**Comment by ataffanel** [comment]
Yes the Crazyflie 1 is pretty tight in RAM, I am going to look if I can free some ram somewhere else as well.

**Comment by ograff** [comment]
Hmm, I can't seem to figure out how I could coerce the data from the registers into the Log group in any useful way. Perhaps reducing other RAM usage is the best option.

**Comment by ataffanel** [comment]
I freed some RAM by moving the led sequence in flash, so now it should fit in CF1.

Thanks!

**Pull request merged**
