### PR TITLE
vendor: Upgrade CMSIS from 4.5.0 to 5.7.0

### PR DESCRIPTION
**Pull request by concatime**
CMSIS 4 is a [legacy version](//github.com/ARM-software/CMSIS/tree/master#cmsis-version-4-legacy-repository) and as @whoenig told me in https://github.com/bitcraze/crazyflie-firmware/pull/708#issuecomment-789251361:
> I don't see a reason for not upgrading CMSIS.

The only difference I found in code between CMSIS 4 and 5 is that the latter offers two versions of `arm_bitreversal2`:
https://github.com/ARM-software/CMSIS/blob/master/CMSIS/DSP_Lib/Source/TransformFunctions/arm_bitreversal2.S
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/DSP/Source/TransformFunctions/arm_bitreversal2.S
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/DSP/Source/TransformFunctions/arm_bitreversal2.c

The `Makefile` would automatically pick the C version when the target is solely `DSP_OBJ += arm_bitreversal2.o`: https://github.com/bitcraze/crazyflie-firmware/blob/master/tools/make/cmsis_dsp/obj.mk#L273. That’s why `CSFLAGS` is not required anymore. I removed `__TARGET_FPU_VFP` like https://github.com/bitcraze/crazyflie-firmware/pull/709. I also removed the unused includes `$(CRAZYFLIE_BASE)/src/utils/interface/clockCorrection` and `(CRAZYFLIE_BASE)/src`. Finally, I sorted the targets.

With https://github.com/bitcraze/crazyflie-firmware/issues/713 and this, this repo. would be buildable with Clang.

I need reviews of this PR.
Thank you in advance.

### CODE REVIEW

**Comment by concatime** [comment]
There is something off with the CI. I have no issues on my end.

**Comment by ataffanel** [comment]
Looks good to me! i had to run ```git submodule sync``` to be able to pull the new submodule, but except for that everything work including the unit tests.

The PR is still marked [WIP] but if you have nothing to add to it, I can merge it.

**Comment by concatime** [comment]
I was waiting for https://github.com/bitcraze/crazyflie-firmware/pull/714 to get merge. All conflits are not resolved.

**Comment by ataffanel** [comment]
Merging, thanks!

**Pull request merged**
