### PR TITLE
release workflow for actions

### PR DESCRIPTION
**Pull request by knmcguire**
Started with integrating the firmware release into github actions. This used to be on Jenkins

### CODE REVIEW

**Comment by knmcguire** [comment]
Currently I don't have the DFU file in as it is unsure if actions also support an upload of that file, but perhaps it can work with the same asset type as with  the bin file. 

The idea is, is that the same steps will be done for the other platforms as well (building and uploading assets)

**Comment by krichardsson** [comment]
Looking good! 

Is the `- name: Upload Build Artifact` really required? Looks like the artifacts are uploaded to the release later

Is the plan to add some sort of matrix build with cf2, tag and bolt?

**Comment by knmcguire** [comment]
Ah yeah ofcourse, we dont that extra upload here. That is being used by crazy flie testing CI at ci.yml. I was planning to simply copy paste it like in the build ci, but using a matrix sounds cleaner. I'll try it!

Btw @krichardsson were you able to try out the action out before officially merging? Or does it need to be fully in master for us to try it out

**Comment by knmcguire** [comment]
Got the idea to seperate the release and upload bin files from this issue: https://github.com/actions/create-release/issues/14#issuecomment-555379810

**Comment by krichardsson** [comment]
Looks good! 
It seems as github thinks something is wrong on line 56 though, https://github.com/bitcraze/crazyflie-firmware/actions/runs/2023276547

**Comment by knmcguire** [comment]
ahhh so it does check the yml workflow file everytime. interesting! I've fixed it so let's see

**Pull request merged**
