### PR TITLE
add peer_localization to store the position of other crazyflies

### PR DESCRIPTION
**Pull request by Zhenghao-Dai**
#567 In our discussion about implementing the collision avoidance, @krichardsson suggests that we put the position of other crazyflies in its own module. @jpreiss

### CODE REVIEW

**Comment by krichardsson** [comment]
Thanks for the pull request!

It looks good, but I have a couple minor comments:

1. The type "struct otherPosition:"
    1. We tend to typedef structs, see for instance https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/interface/stabilizer_types.h#L57
    1.  We also try to name types based on the module to get some sort of "name space"  (previous is not a good example :-)), for instance this type should maybe be called peerLocalizationOtherPosition_t. There are no clear guidelines on naming, sorry!
    1. You could use the type point_t (in the example above), it already contains a timestamp if you want to
    1. It is probably enough to use a uint32_t for the timestamp

2. The size of the NUM_MAX_NEIGHBORS is fairly large considering that this functionality probably will be used by a limited number of users, in combination with that we are starting to be low on RAM. I'm not sure what a "normal" use case is for this module? What would make sense?

**Comment by jpreiss** [comment]
Re. 1: @Zhenghao-Dai can you update the pull request? I think we can use the `point_t` as suggested. No need to add a redundant type.

Re. 2: I'm not sure about `NUM_MAX_NEIGHBORS`. I think 10 would be enough for most uses.

Users can always recompile and flash the firmware to support larger teams, but that gets more and more tedious as the number increases. Something like the dynamic memory allocation currently used to support long polynomial trajectories would be ideal.

Would it make sense to have a `peerLocalizationNumNeighbors` param that triggers a dynamic memory allocation when it changes? The default value could be zero. I think it would be reasonable to assume that this param will only change once after firmware bootup, so we can avoid worrying about memory fragmentation.

@whoenig any thoughts?

**Comment by Zhenghao-Dai** [comment]
Updated

**Comment by jpreiss** [comment]
@Zhenghao-Dai I think this CI build failure is related to copying the comments from Zoom chat, like we saw before. Try retyping the comments yourself.

**Comment by Zhenghao-Dai** [comment]
Fixed and passed @jpreiss

**Comment by krichardsson** [comment]
Merged. Thanks!

**Pull request merged**
