### PR TITLE
Introducing Flapper platform

### PR DESCRIPTION
**Pull request by matejkarasek**
This PR adds a "flapper" platform, together with default settings and gain values.
- To enable servomotors, which need a non-zero neutral value, additions were made to Motors.c and supervisor.c
- depends on PRs #1121 and #1122, which are also included in this PR

### CODE REVIEW

**Comment by knmcguire** [comment]
Could you resolve the build issue that the CI caught? You can check out the log in details

**Comment by krichardsson** [comment]
Does this PR depend on 1122? Does it have to be merged first?

**Comment by matejkarasek** [comment]
> Does this PR depend on 1122? Does it have to be merged first?

I have included the original commits from #1122 (and #1121) also in this PR, so it is already merged (but needs to get updated).

I am working on fixing the remaining issues.
Next to the feed-forward gains mentioned in the discussion of #1122 but left out eventually, I have see redefinition issues with when multiple power distributions are used, will see, what can be done about that

**Comment by krichardsson** [comment]
@matejkarasek maybe you should consider creating a new PR for adding the flapper?
I have merged your other two PRs and I think it would be cleaner to make a new branch from master for this PR. Currently this PR contains all the changes from the other two and it is hard to understand what is flapper related.

I have also merged a PR that updates the build scripts a bit and all you have to do build flapper in CI is to add i to the `build_targets.json` file

**Comment by matejkarasek** [comment]
Yes, will do that soon, thanks!

**Pull request closed without merging**
