### PR TITLE
Master.mag driver fixes

### PR DESCRIPTION
**Pull request by stephanbro**
I've fixed the configuration of the mag so the values are updated properly now when using the sensors task and kalman estimator.

The barometer isn't working right now and I was planning on tackling that next.

### CODE REVIEW

**Comment by tobbeanton** [comment]
Many thanks for this fix! I'm curious what moving  mpu6500SetClockSource(MPU6500_CLOCK_PLL_XGYRO); does?

**Comment by tobbeanton** [comment]
I will check with a i2c analyser to see how the reading behaves. Then we know if it is better to revert it.

**Comment by tobbeanton** [comment]
After checking the i2c log I can say it behaves pretty well so no need to revert it. One thought i got after looking att the sensors_task way of reading the magnetometer is to do the same in imu_cf2. That is reading x,y,z and ST2 (overflow) in one read.

By the way, in the long run I think we should move the sensors_task way of reading using the MPU9250 master into imu_cf2 and make them use the same API and not have duplicated code.

**Comment by stephanbro** [comment]
That's great to hear! I was thinking the same thing about moving a lot of the sensors task code over to the imu_cf2 module. There is a fair bit of cleanup that can be done on the slave reading and writing also.

**Pull request merged**
