### PR TITLE
Enabling PID position control in body-aligned coordinates

### PR DESCRIPTION
**Pull request by matejkarasek**
This PR allows to control the position and velocity in body-aligned coordinates, instead of global coordinates (currently the only option). The change only affects the PID controller.
This functionality is useful when flying with non-symmetric vehicles whose flight dynamics along x and y directions are not the same, and thus require different gain tuning.
It can be turned on and off through a define POSITION_CONTROL_IN_BODY.

Further updates in this PR:
- low pass filters in the position and control loops are now separated: position and velocity as well as xy and z directions can be set separately
- the above settings can be changed through configuration parameters
- feed-forward terms and gains were added for the velocity loop (useful for vehicles with non-negligible drag)

### CODE REVIEW

**Comment by knmcguire** [comment]
Hi!

It is an interesting point though, but perhaps there is some discussion necessary for this first. The firmware was initially built to work for a quadcopter mainly but with the bolt it's been expanding a lot now. Theoratically perhaps, I would vote that the the lower level controllers are the ones that are different for different platforms but reality proves that will be difficult.

The current problem with PR is that the velocity_body boolean now makes it a bit complicated, and more over, 2 different controllers complicates the code even further... 

I was thinking, since the PID gains for the crazyflie is the same for the x and y position and velocity controller due to the symmetry, doesn't it make sense to replace the global coordinate PID based controller entirely with a body fixed one? Technically  as long as the state and setpoint are rotated correctly, the control result should be completely similar, don't you think @matejkarasek ? 

I'll also discuss this internally

**Comment by knmcguire** [comment]
I've discussed it with some here, and there are a couple of factors. 

First of all, we need to have a good look at the way we handle the setpoint modes (relative vs global, position vs velocity) as that currently not super logical. But this is part of a bigger discussion of the whole framework and is probably not part of this pull request (maybe I'll make a separate issue to discuss this)

Second, I do think that it will not make a difference for the crazyflie if we would make the controller in body standard. However, since more rotations are done for the in body controller, there might be more CPU load because of it, albeit it probably is just small. 

The one who original implemented the PID controller is @ataffanel, so once he is back from his holiday, I'll involve him in the discussion.

**Comment by matejkarasek** [comment]
Hi Kimberly,
Thanks for looking into this!

Yeah, I am aware that this affects the core functionality, that is why I make this optional... But I agree there is now maybe too many options. The velocity_body boolean indeed increases the complexity even further...

I personally think that control in the body coordinates makes more sense for any platform, and should indeed make no big difference if implemented correctly for symmetric platforms (most quad/multi copters).

This does not necessarily introduce more body rotations - even with the current control in global coordinates, you need to rotate the output eventually since attitude control is done around body-fixed axes.
With control in body coordinates you just do this rotation earlier.

**Comment by matejkarasek** [comment]
As for the setpoints and their structure, I agree this for for a larger discussion and outside of the scope of this PR.
But already removing the velocity_body boolean and having a function instead that will rotate the setpoint from the user to the setpoint coordinates (be it global or body-fixed) could make things a bit simpler?

**Comment by ataffanel** [comment]
I do not have much input about the functionality in itself. Velocity in the body coordinate system makes some sense to have onboard and supporting asymmetrical platforms is most likely going to be nice to have for the CF Bolt. I cannot wrap my head around body-aligned position control though, but I can accept that it is useful :).

As for the set-point structure: my point of view is that it is better to put these king of info in the set-point structure mostly if the alternative is to add a new state to the controllers: with the current approach there is never uncertainty on what the controller should do since we pass control parameters for each setpoints, if the setpoint meaning is an external state we start having problems like synchronization issues: for which setpoint in the stream does the parameter change. So, making the structure narrower in scope and more adapted to real-life limitations like discussed in #577 sounds better to me.

**Comment by matejkarasek** [comment]
@ataffanel The body aligned position control seems a bit strange indeed, but think of it as if you were sitting on board: How much forward/backward and how much left/right do I need to go. 
If the xy gains are identical, this will make no difference.

I see your point with the setpoints... I think the current situation is acceptable, just the code around the velocity_body boolean requires some attention when reading it, as it is not so straightforward.

So if there is no objection against including this functionality, would you prefer to:
1) Let the user decide what to use using the defines as it is implemented now (advantage: safer for current users, disadvantage: more code to maintain)
2) Switch to "in body" by default (simpler code, but some extra transformations needed as the states are saved in global coordinates)

Thanks!

**Comment by matejkarasek** [comment]
I have resolved the conflicts with the current master. 
Any thoughts on this PR in the meantime? :)

**Comment by matejkarasek** [comment]
Closing, replaced by #885

**Pull request closed without merging**
