### PR TITLE
HeadFree mode added

### PR DESCRIPTION
**Pull request by capriele**
I've implemented CareFree mode into de firmware... this is the code (stabilizer.c)

### CODE REVIEW

**Comment by tobbeanton** [comment]
I've tested the pull request and the CareFree mode works great. There are however some commented code, unused code which would be bad to integrate. Can you clean up the pull request or divide it up in several pull request?

I have a hard time understanding what this code does in the stabalizer@259:
       complementaryFilter(acc, gyro, &eulerRollDesired, &eulerPitchDesired);

**Comment by capriele** [comment]
Yes I can. In the pull there is lot of unuseful code so i clean it.

**Comment by ibrahima** [comment]
Actually, the first commit 466911f is sufficient for the CareFree mode, the rest is not really related or necessary and would probably be better as a separate commit, right? I'm running that on my CF 2.0 and it works much better than the default because of the yaw drift from the gyro. But the other commits won't merge cleanly on the crazyflie2 branch so it's probably better to isolate the CareFree mode from the other improvements.

Thanks for the commit! It's really helpful for me.

**Comment by tobbeanton** [comment]
I integrated the Carefree mode code in https://github.com/bitcraze/crazyflie-firmware/commit/7cc43495522b55036631c8bc66b0033375f83816 commit. Thanks for the code!

**Pull request closed without merging**
