### PR TITLE
Update usddeck.c

### PR DESCRIPTION
**Pull request by roeeSch**
Support config.txt files with lines which are pure comments such as the first line here:
```
# Config Vesion 1.2.3
100   # frequency
3    # buffer size
...
gyro.x
gyro.y
gyro.z
acc.x
```

### CODE REVIEW

**Comment by knmcguire** [comment]
Ah great, thanks!

This will fix this following issue #915? I wanted to look at this for a triage meeting but perhaps not necessary anymore!

We are in the middle or a release so we might wait a bit with merging this, but in the mean time @tobbeanton could take a look at it!

**Comment by roeeSch** [comment]
@knmcguire, I think this will fix #915.
I verified this functionality by updating the firmware and adding a comment to config.txt and checking the logs on the SD.

**Comment by krichardsson** [comment]
Merged
Thanks!

**Comment by krichardsson** [comment]
Fixes #915

**Pull request merged**
